dir: ../2026/pandora-2026-submissions/
tests: ./test/shortTestSuite.json
ref: ../2026/pandora-2026-the_awesome_teachers_2026/target/pandora.jar
output: reports
phases:
  teacher_evaluation: true
  validation: false
  self_evaluation: false
  cross_testing: false
